version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --stacktrace --info --debug

test_script:
  - gradlew.bat check --stacktrace --info --debug

on_finish:
  - gradlew.bat --stop

cache:
  - .gradle
  - .\gradle
  - C:\Users\appveyor\.gradle
  - C:\Users\appveyor\.ivy2
  - C:\Users\appveyor\.m2

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

platform:
  - x86
  - x64

matrix:
  fast_finish: true